# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detect.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'detect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65tect.proto\x12\x06\x64\x65tect\"#\n\rDetectRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"A\n\x0c\x44\x65tectResult\x12\x0b\n\x03\x62ox\x18\x01 \x03(\x02\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08\x63lass_id\x18\x03 \x01(\x05\"P\n\x0e\x44\x65tectResponse\x12%\n\x07results\x18\x01 \x03(\x0b\x32\x14.detect.DetectResult\x12\x17\n\x0fprocessed_image\x18\x02 \x01(\x0c\x32\x43\n\x08\x44\x65tector\x12\x37\n\x06\x44\x65tect\x12\x15.detect.DetectRequest\x1a\x16.detect.DetectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTREQUEST']._serialized_start=24
  _globals['_DETECTREQUEST']._serialized_end=59
  _globals['_DETECTRESULT']._serialized_start=61
  _globals['_DETECTRESULT']._serialized_end=126
  _globals['_DETECTRESPONSE']._serialized_start=128
  _globals['_DETECTRESPONSE']._serialized_end=208
  _globals['_DETECTOR']._serialized_start=210
  _globals['_DETECTOR']._serialized_end=277
# @@protoc_insertion_point(module_scope)
